name: Multi-arch clash build & release

on:
  # 手动触发时可输入版本号 tag（如 v1.2.3）
  workflow_dispatch:
    inputs:
      clash_version:
        description: '指定 Clash 版本号（如 v1.18.0 或 latest）'
        required: true
        default: '1.18.0'


permissions:
  contents: write    # 需要写权限以便创建 release / tag
  packages: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout specified repository
        uses: actions/checkout@v4
        with:
          # 显式指定仓库（owner/repo）
          repository: 'Ieooo/clash'
          # 如果需要拉取特定 ref，可改为 refs/tags/${{ github.event.inputs.tag }} 或 github.ref
          fetch-depth: 0

      - name: 安装 Go 1.25.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
      - name: Set timezone to Asia/Shanghai
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          date

      - name: 编译 Clash
        run: |
          ls
          mkdir -p build
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}
          export VERSION=${{ github.event.inputs.clash_version }}
          CURRENT_TIME=$(date '+%Y-%m-%d_%H-%M-%S')
          echo "开始编译: ${GOOS}-${GOARCH} (${VERSION})"

          if [[ "$GOOS" == "windows" ]]; then
            OUTFILE="build/clash.exe"
          else
            OUTFILE="build/clash"
          fi
          # go mod init
          go build -ldflags \
          "-X 'github.com/Ieooo/clash/constant.Version=${VERSION}' -X 'github.com/Ieooo/clash/constant.BuildTime=${CURRENT_TIME}'" \
          -o ${OUTFILE}

          cd build
          if [[ "$GOOS" == "windows" ]]; then
            zip clash-${GOOS}-${GOARCH}-${VERSION}.zip clash.exe
          else
            tar -czf clash-${GOOS}-${GOARCH}-${VERSION}.tar.gz clash
          fi
          cd ..
      - name: 上传产物到 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clash-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.inputs.clash_version }}
          path: build/clash-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.inputs.clash_version }}.*

  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 下载所有产物
        uses: actions/download-artifact@v4
        with:
          path: release-files

      - name: 创建 Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "Clash_${{ github.event.inputs.clash_version }}"
          name: "Clash ${{ github.event.inputs.clash_version }}"
          files: release-files/**/*
          draft: false
          prerelease: false
          body: |
            clash build clash ${{ github.event.inputs.clash_version }}
            平台打包说明：
            - Linux/macOS: tar.gz
            - Windows: zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
