name: lx-netease-music-mobile build & release

on:
  # 手动触发时可输入版本号 tag（如 v1.2.3）
  workflow_dispatch:
    inputs:
      tags:
        description: '指定 Clash 版本号（如 v1.18.0 或 latest）'
        required: true
        default: '1.18.0'


permissions:
  contents: write    # 需要写权限以便创建 release / tag
  packages: write
  issues: write

jobs:
 Android:
    name: Android
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout specified repository
        uses: actions/checkout@v4
        with:
          # 显式指定仓库（owner/repo）
          repository: 'souvenp/lx-netease-music-mobile'
          # 如果需要拉取特定 ref，可改为 refs/tags/${{ github.event.inputs.tag }} 或 github.ref
          fetch-depth: 0

      - name: Setup Env
        uses: ./.github/actions/setup

      - name: Build Packages
        shell: bash
        run: |
          cd android
          echo ${{ secrets.MYAPP_KEYSTORE_BASE64 }} | base64 --decode > app/${{ secrets.MYAPP_UPLOAD_STORE_FILE }}
          chmod +x ./gradlew
          ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_FILE='${{ secrets.MYAPP_UPLOAD_STORE_FILE }}' -PMYAPP_UPLOAD_KEY_ALIAS='${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }}' -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}'
          rm -f app/${{ secrets.MYAPP_UPLOAD_STORE_FILE }}

      # Push tag to GitHub if package.json version's tag is not tagged
      - name: Get package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Create git tag
        uses: pkgdeps/git-tag-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ env.PACKAGE_VERSION }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: 'v'

      - name: Generate file MD5
        run: |
          cd android/app/build/outputs/apk/release
          md5sum *.apk

      - name: Upload Artifact
        uses: ./.github/actions/upload-artifact
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

 Release:
  name: Release
  runs-on: ubuntu-latest
  needs: [Android]
  steps:
    - name: Check out git repository
      uses: actions/checkout@v4
      with:
          # 显式指定仓库（owner/repo）
          repository: 'souvenp/lx-netease-music-mobile'
          # 如果需要拉取特定 ref，可改为 refs/tags/${{ github.event.inputs.tag }} 或 github.ref
          fetch-depth: 0

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
        merge-multiple: true

    - name: Generate release body
      run: |
        awk 'BEGIN{RS="---"}{if(NR==1)print $0}' ./publish/changeLog.md > RELEASE_NOTES.md
        echo -e '\n### File MD5\n```' >> RELEASE_NOTES.md
        cd artifacts
        md5sum *.apk >> ../RELEASE_NOTES.md
        cd ..
        echo -e '```\n' >> RELEASE_NOTES.md
        echo -e '\n[软件安装包说明](https://lyswhut.github.io/lx-music-doc/download#%E8%BD%AF%E4%BB%B6%E5%AE%89%E8%A3%85%E5%8C%85%E8%AF%B4%E6%98%8E)\n' >> RELEASE_NOTES.md

    - name: Get package version
      run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: RELEASE_NOTES.md
        prerelease: false
        draft: false
        tag_name: lx-netease-music-mobile-v${{ env.PACKAGE_VERSION }}
        files: |
          artifacts/lx-netease-music-mobile-v${{ env.PACKAGE_VERSION }}-arm64-v8a.apk
          artifacts/lx-netease-music-mobile-v${{ env.PACKAGE_VERSION }}-armeabi-v7a.apk
          artifacts/lx-netease-music-mobile-v${{ env.PACKAGE_VERSION }}-x86_64.apk
          artifacts/lx-netease-music-mobile-v${{ env.PACKAGE_VERSION }}-x86.apk
          artifacts/lx-netease-music-mobile-v${{ env.PACKAGE_VERSION }}-universal.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

